version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: resume-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resumedb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - resume-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis缓存
  redis:
    image: redis:6.2-alpine
    container_name: resume-redis
    ports:
      - "6379:6379"
    networks:
      - resume-network

  # Kafka消息队列
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: resume-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - resume-network

  kafka:
    image: bitnami/kafka:3.1
    container_name: resume-kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - resume-network

  # 用户服务
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: resume-user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/resumedb?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # 微信开发模式配置
      - WECHAT_DEV_MODE=true
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge

volumes:
  mysql-data:
